name: Render
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: johnbeynon/render-deploy-action
        with:
        	service-id: ${{ secrets.some-render-service-id }}
        	api-key: ${{ secrets.render-api-key }}
